local opts = { noremap = true, silent = true }

new_keymap("n", "\\n", function()
    cmd("cnext")
end, opts)
new_keymap("n", "\\o", function()
    cmd("copen")
end, opts)
new_keymap("n", "\\c", function()
    cmd("cclose")
end, opts)
new_keymap("n", "\\p", function()
    cmd("cprevious")
end, opts)
new_keymap("n", "\\l", function()
    cmd("cexpr []")
end, opts)
