require("usr.util")
require("usr.core.autocmds")
require("usr.core.settings")
require("usr.core.keymaps")
require("usr.util.plugins").try_bootstrap_packer()
require("usr.colors")
require("usr.modules")
