require("usr.util")
require("usr.core.autocmds")
require("usr.core.settings")
require("usr.core.keymaps")
local colors = require("usr.colors")
colors.setup()
require("usr.modules")
colors.load_colorscheme()
