_G.niscolas = {
    icons = {
        add = "",
        class = "",
        color = "",
        constant = "",
        constructor = "",
        directory = "",
        change = "",
        enum = "",
        enum_member = "",
        error = "",
        event = "",
        field = "",
        file = "",
        fn = "",
        hint = "",
        info = "",
        interface = "",
        keyword = "",
        method = "",
        remove = "",
        module = "",
        operator = "",
        property = "",
        reference = "",
        snippet = "",
        struct = "",
        text = "",
        type_parameter = "",
        unit = "",
        value = "",
        variable = "",
        warning = "",
    },
    settings = {
        os_name = os.getenv("OS_NAME"),
        setup = os.getenv("NISCOLAS_SETUP"),
    },
    theme = {
        name = "gruvbox-flat",
        feline_theme_name = "gruvbox-flat",
        fzf_theme_name = "gruvbox-flat",
        custom_module_name = "gruvbox-flat",
        use_transparency = true,
    },
}
